# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'

target 'TodoApp' do
  pod 'MagicalRecord'
end

target 'TodoAppTests' do

end

target 'TodoAppUITests' do

end

