source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'QiitaAPISample' do
  pod 'Alamofire'
  pod 'ObjectMapper'
end

target 'QiitaAPISampleTests' do

end

target 'QiitaAPISampleUITests' do

end

